### PR TITLE
Update build target gates

### PR DESCRIPTION
**Pull request by hwh33**
I checked all of these links and they're still valid, so we should be good to go.

If you're coming here from the future, wondering how to make this repo build for Go 1.17+, here are a few pointers: This repo utilizes a few unexported types and functions from the standard library, using `go:linkname` directives.  When building with a new version of Go, we need to check to make sure these linked types and functions still exist; the compiler will not check for us and we'll get weird runtime failures if the links are broken.

To update, go to each file with a `!go1.17` build constraint.  Search the file for `go:linkname` directives.  Search the standard library Go 1.17 source code for each of the linked names (e.g. `grep -nw "func entersyscallblock" $GOROOT/src/runtime/*`).  If the standard-library file defining the name has build constraints, double-check that these still support netstack's use of the name.  Once each of the linked names in a file are verified, update the build constraint to exclude the next version of Go, forcing this check again on the next update to the standard library.

### CODE REVIEW

File: sleep/compile_error.go [hunk 1]
```diff
@@ -0,0 +1,6 @@
+// +build go1.17
+
+package sleep
+
+// Force a compile error to "output" a message.
+const compileError int = "This package requires manual checks before it can be built on Go 1.17+. See https://github.com/getlantern/netstack/pull/6"
```
Comment (hwh33) [inline sleep/compile_error.go:6]: I'm curious what you all think of this.  The idea is that somebody building a dependent package (e.g. flashlight) would see this and follow the link:

```
# github.com/google/netstack/tcpip/link/rawfile
tcpip/link/rawfile/compile_error.go:6:7: cannot use "This package requires manual checks before it can be built on Go 1.17+. See https://github.com/getlantern/netstack/pull/6" (type untyped string) as type int
tcpip/link/rawfile/rawfile_unsafe.go:137:10: undefined: BlockingPoll
tcpip/link/rawfile/rawfile_unsafe.go:159:10: undefined: BlockingPoll
tcpip/link/rawfile/rawfile_unsafe.go:189:14: undefined: BlockingPoll
```

instead of just the "undefined" errors which may be confusing without context.

**Comment by anacrolix** [comment]
@hwh33 is there a way to build for arbitrary Go versions *after* the last change? Say nothing changes in go 1.17, or 1.18, just continue using what worked for 1.16?

**Comment by hwh33** [comment]
I don't think I quite understand your question @anacrolix.  I think the expectation is that nothing will change in Go 1.17, but we still unfortunately should do this same manual check when we transition to Go 1.17.  The issue is that the compiler will not catch missing names for us.  We would likely just get some odd crash at runtime.

**Comment by anacrolix** [comment]
Thanks, I didn't know that!

File: sleep/compile_error.go (hunk 1 above)
Comment (anacrolix) [reply sleep/compile_error.go:6]: Looks good. I can't find a way to do this with some Go compiler directive. I'm sure something existed, but it does seem like it would be out of line with Go conventions.

**Review by anacrolix — APPROVED** [review]
I still wonder if maybe the crash is better, that is why we have tests after all. It's a lot of work to be manually updating this stuff.

**Review by jmorag — APPROVED** [review]
Not much to say about the implementation details, but can confirm that pointing flashlight to this branch allows me to build with go-1.16.

**Comment by myleshorton** [comment]
I'm going to pull this in so we can run on 1.16. I personally think catching it compile time versus runtime is a win, but we can change it later if desired!

File: sleep/compile_error.go (hunk 1 above)
Comment (hwh33) [reply sleep/compile_error.go:6]: Yeah I wasn't able to find any such directive and I agree it would be out of line with Go conventions.

**Comment by hwh33** [comment]
Sorry @anacrolix I don't know why, but I missed your comments earlier!

> I still wonder if maybe the crash is better, that is why we have tests after all. It's a lot of work to be manually updating this stuff.

I don't personally have enough confidence that our tests enter code paths which hit one of these linked functions.  Maybe we could devise such a test?  Then we'd want to make sure every dependent library includes such a test.  I'm not sure that's any less work... just a little more up-front.  Actually I'm kind of curious to explore this, so I might give it a shot.

Anyway, it sounds like the real fix is to explore using gvisor at some point.

Thanks for the merge @myleshorton!
